(()=>{
 const products=window.PURCHASE_PRODUCTS,key='netpro-b2b-purchase';let cart=[];
 try{const saved=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(saved))cart=saved.filter(x=>products.some(p=>p.id===x.id&&p.sizes.includes(x.size))&&Number.isInteger(x.quantity)&&x.quantity>0&&x.quantity<=100000);}catch{}
 const money=n=>'$'+n.toFixed(2);
 const dialog=document.createElement('dialog');dialog.id='purchase-dialog';dialog.className='bag-dialog purchase-dialog';dialog.innerHTML='<div class="purchase-inner"><h2>Shopping cart</h2><div id="purchase-items"></div><div id="purchase-summary"></div></div>';document.body.append(dialog);
 function render(){document.querySelector('#purchase-items').innerHTML=cart.map((x,i)=>{const p=products.find(p=>p.id===x.id);return `<article class="purchase-item"><div class="product-art art-${p.art}"></div><div><h3>${p.name}</h3><p>${p.color} · ${x.size}</p><div class="purchase-quantity"><button data-purchase-step="${i}" data-step="-1" aria-label="Decrease quantity">−</button><span>${x.quantity}</span><button data-purchase-step="${i}" data-step="1" aria-label="Increase quantity">+</button></div></div><strong>${money(p.price*x.quantity)}</strong><button class="purchase-remove" data-purchase-remove="${i}" aria-label="Remove ${p.name}">×</button></article>`;}).join('')||'<p>Your cart is empty. Browse products and choose Add to cart.</p>';document.querySelector('#purchase-summary').innerHTML=cart.length?`<div class="purchase-costs"><p><span>Items (${cart.reduce((n,x)=>n+x.quantity,0)})</span><strong>${money(cart.reduce((n,x)=>n+products.find(p=>p.id===x.id).price*x.quantity,0))}</strong></p><p><span>Shipping</span><span>Not calculated</span></p><p><span>Taxes</span><span>Not calculated</span></p><label>Promo code<input disabled placeholder="Available when checkout launches"></label></div><div class="subtotal"><span>Subtotal</span><strong>${money(cart.reduce((n,x)=>n+products.find(p=>p.id===x.id).price*x.quantity,0))}</strong></div><p>Shipping and taxes are not included.</p><a class="button primary cart-checkout" href="checkout.html">Continue to checkout →</a><p class="quote-hint">Design preview. Payments and orders are not connected.</p>`:'';const n=cart.reduce((n,x)=>n+x.quantity,0);document.querySelectorAll('.purchase-count').forEach(el=>{el.textContent=n;el.hidden=!n;});}
 function save(){try{localStorage.setItem(key,JSON.stringify(cart));}catch{}render();}
 function open(){document.querySelectorAll('dialog[open]').forEach(d=>d.close());render();dialog.classList.remove('drawer-closing');dialog.showModal();document.body.classList.add('modal-open');}
 function close(){if(dialog.classList.contains('drawer-closing'))return;if(matchMedia('(prefers-reduced-motion: reduce)').matches){dialog.close();return;}dialog.classList.add('drawer-closing');setTimeout(()=>{dialog.close();dialog.classList.remove('drawer-closing');},280);}
 dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
 dialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));
 dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}const step=e.target.closest('[data-purchase-step]');if(step){const i=Number(step.dataset.purchaseStep);cart[i].quantity=Math.min(100000,cart[i].quantity+Number(step.dataset.step));if(cart[i].quantity<1)cart.splice(i,1);save();}const b=e.target.closest('[data-purchase-remove]');if(b){cart.splice(Number(b.dataset.purchaseRemove),1);save();}});
 dialog.addEventListener('change',e=>{if(e.target.matches('[data-purchase-qty]')){cart[Number(e.target.dataset.purchaseQty)].quantity=Math.min(100000,Math.max(1,Math.floor(Number(e.target.value)||1)));save();}});
 document.addEventListener('click',e=>{if(e.target.closest('[data-purchase-open]'))open();const b=e.target.closest('[data-buy]');if(!b)return;const size=document.querySelector('[data-detail-size][aria-pressed=true]').dataset.detailSize;const quantity=Math.min(100000,Math.max(1,Math.floor(Number(document.querySelector('#detail-quantity').value)||1)));const item=cart.find(x=>x.id===b.dataset.buy&&x.size===size);if(item)item.quantity=Math.min(100000,item.quantity+quantity);else cart.push({id:b.dataset.buy,size,quantity});save();open();});
 render();
})();
