(()=>{
 const key='netpro-b2b-enquiry',products=window.NETPRO_PRODUCTS,form=document.querySelector('#quote-form'),container=document.querySelector('#quote-items');
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let items=[];try{const saved=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(saved))items=saved.filter(x=>products.some(p=>p.id===x.id&&p.sizes.includes(x.size))&&Number.isInteger(x.quantity)&&x.quantity>0&&x.quantity<=100000);}catch{}
 function render(){container.innerHTML=items.length?items.map((x,i)=>{const p=products.find(p=>p.id===x.id);return `<article class="quote-item"><div class="product-art art-${p.art}" role="img" aria-label="${esc(p.name)}"></div><div><h3>${esc(p.name)}</h3><p>${esc(p.color)} · ${esc(x.size)}</p><label>Requested units<input data-qty="${i}" type="number" min="1" max="100000" value="${x.quantity}"></label><button type="button" data-remove-quote="${i}">Remove</button></div></article>`;}).join(''):'<p class="quote-empty">No products selected yet. Describe your requirements in the form, or browse our product range.</p>';}
 function save(){try{localStorage.setItem(key,JSON.stringify(items));}catch{} window.dispatchEvent(new Event('enquiry-updated'));render();form.elements.quantity.value=items.reduce((n,x)=>n+x.quantity,0)||'';}
 container.addEventListener('change',e=>{if(!e.target.matches('[data-qty]'))return;items[Number(e.target.dataset.qty)].quantity=Math.min(100000,Math.max(1,Math.floor(Number(e.target.value)||1)));save();});
 container.addEventListener('click',e=>{const b=e.target.closest('[data-remove-quote]');if(b){items.splice(Number(b.dataset.removeQuote),1);save();}});
 render();form.elements.quantity.value=items.reduce((n,x)=>n+x.quantity,0)||'';
 form.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity())return;const status=document.querySelector('#quote-status'),button=form.querySelector('button[type=submit]'),originalLabel=button.textContent,d=new FormData(form);const setStatus=(kind,msg)=>{status.className='form-status'+(kind?' is-'+kind:'');status.textContent=msg;};const payload={company:d.get('company'),name:d.get('name'),email:d.get('email'),destination:d.get('destination'),project:d.get('project'),quantity:d.get('quantity'),decoration:d.get('decoration'),date:d.get('date'),sample:d.get('sample'),budget:d.get('budget'),artwork:d.get('artwork'),brief:d.get('brief'),website:d.get('website')||'',items:items.map(x=>{const p=products.find(p=>p.id===x.id);return {name:p.name,color:p.color,size:x.size,quantity:x.quantity};})};button.disabled=true;button.textContent='Sending…';setStatus('sending','Sending your enquiry…');
 try{const res=await fetch('/api/quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!res.ok){const data=await res.json().catch(()=>null);throw new Error((data&&data.error)||'Request failed');}items=[];save();form.reset();setStatus('success','✓ Enquiry sent successfully. A confirmation email has been sent to your inbox.');}catch(err){setStatus('error',err.message&&err.message!=='Request failed'?err.message:'Sorry, your enquiry could not be sent right now. Please try again in a moment.');}finally{button.disabled=false;button.textContent=originalLabel;}});
})();