(()=>{
 const key='netpro-b2b-enquiry',products=window.NETPRO_PRODUCTS,form=document.querySelector('#quote-form'),container=document.querySelector('#quote-items');
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let items=[];try{const saved=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(saved))items=saved.filter(x=>products.some(p=>p.id===x.id&&p.sizes.includes(x.size))&&Number.isInteger(x.quantity)&&x.quantity>0&&x.quantity<=100000);}catch{}
 function render(){container.innerHTML=items.length?items.map((x,i)=>{const p=products.find(p=>p.id===x.id);return `<article class="quote-item"><div class="product-art art-${p.art}" role="img" aria-label="${esc(p.name)}"></div><div><h3>${esc(p.name)}</h3><p>${esc(p.color)} · ${esc(x.size)}</p><label>Requested units<input data-qty="${i}" type="number" min="1" max="100000" value="${x.quantity}"></label><button type="button" data-remove-quote="${i}">Remove</button></div></article>`;}).join(''):'<p class="quote-empty">No products selected yet. Describe your requirements in the form, or browse our product range.</p>';}
 function save(){try{localStorage.setItem(key,JSON.stringify(items));}catch{} window.dispatchEvent(new Event('enquiry-updated'));render();form.elements.quantity.value=items.reduce((n,x)=>n+x.quantity,0)||'';}
 container.addEventListener('change',e=>{if(!e.target.matches('[data-qty]'))return;items[Number(e.target.dataset.qty)].quantity=Math.min(100000,Math.max(1,Math.floor(Number(e.target.value)||1)));save();});
 container.addEventListener('click',e=>{const b=e.target.closest('[data-remove-quote]');if(b){items.splice(Number(b.dataset.removeQuote),1);save();}});
 const files=document.querySelector('#artwork-file');files.addEventListener('change',()=>{const selected=Array.from(files.files);const invalid=selected.length>3||selected.some(f=>f.size>10*1024*1024);if(invalid)files.value='';document.querySelector('#artwork-file-status').textContent=invalid?'Please select up to 3 files, each no larger than 10 MB.':selected.map(f=>f.name).join(' · ');});
 render();form.elements.quantity.value=items.reduce((n,x)=>n+x.quantity,0)||'';
 function brief(){const d=new FormData(form);return 'NETPRO — BULK & CUSTOM ENQUIRY\n\n'+['company','name','email','destination','project','quantity','decoration','date','sample','budget','artwork','placement'].map(k=>k.toUpperCase()+': '+(d.get(k)||'Not specified')).join('\n')+'\n\nPRODUCT SHORTLIST\n'+(items.map(x=>{const p=products.find(p=>p.id===x.id);return `${p.name} | ${p.color} | ${x.size} | ${x.quantity} units`;}).join('\n')||'See project brief')+'\n\nARTWORK FILES (attach manually)\n'+Array.from(document.querySelector('#artwork-file').files).map(f=>f.name).join(', ')+'\n\nPROJECT BRIEF\n'+d.get('brief');}
 form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;location.href='mailto:info@netpropatches.com?subject='+encodeURIComponent('Bulk enquiry — '+form.elements.company.value)+'&body='+encodeURIComponent(brief());document.querySelector('#quote-status').textContent='Your email draft has been requested. Review and send it in your email app. If it does not open, contact info@netpropatches.com.';});
})();